# Generated by Django 5.1.1 on 2024-09-29 17:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_joke'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='user',
        ),
        migrations.AddField(
            model_name='joke',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='JokeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.joke')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'joke')},
            },
        ),
    ]
